apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloexpress-deployment
  namespace: test-express
  labels:
    app: helloexpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloexpress
  template:
    metadata:
      labels:
        app: helloexpress
    spec:
      containers:
        - name: helloexpress
          image: nextzeus/helloexpress:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloexpress1-deployment
  namespace: test-express
  labels:
    app: helloexpress1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloexpress1
  template:
    metadata:
      labels:
        app: helloexpress1
    spec:
      containers:
        - name: helloexpress1
          image: nextzeus/helloexpress1:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3001
