apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: keymetrics/pm2:latest-alpine
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
          volumeMounts: # node container dir -> Pod host dir
            - mountPath: /data/code
              name: code-volume
            - mountPath: /data/logs
              name: logs-volume
          workingDir: /data/code
          command: ["/bin/sh", "-c", "pwd && ls -la && npm run start"]
      volumes: # Pod上的目录
        - name: code-volume
          gitRepo:
            repository: https://github.com/NextZeus/k8s-deploy-nodejs-app.git
            revision: master
            directory: .
        - name: logs-volume
          hostPath:
            path: /data/logs/k8s
            type: DirectoryOrCreate
